services:
  stats-db:
    image: postgres:15
    container_name: stats_postgres
    environment:
      POSTGRES_DB: statsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - stats_data:/var/lib/postgresql/data

  stats-server:
    build: ./statService/stat-server
    container_name: stat_server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/statsdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SERVER_PORT: 9090
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

  ewm-db:
    image: postgres:16.1
    container_name: ewm_postgres
    environment:
      POSTGRES_DB: ewmdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ewm_data:/var/lib/postgresql/data

  ewm-service:
    build: ./ewm-service
    container_name: ewm_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewmdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      WAIT_FOR_HOST: stats-server
      WAIT_FOR_PORT: 9090
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server

volumes:
  stats_data:
  ewm_data: